AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Youtube Palette Scraper

Parameters:
  TableName:
    Type: String
    Default: 'YoutubeVideos'

Globals:
  Function:
    Runtime: nodejs14.x

Resources:
  SubmitVideo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/demoPut.demoHandler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref YoutubeVideos
      Environment:
        Variables:
          TABLE_NAME: !Ref YoutubeVideos
      Events:
        NewVideo:
          Type: Api
          Properties:
            Path: /submit
            Method: post
  GetVideo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/demoGet.demoHandler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref YoutubeVideos
      Environment:
        Variables:
          TABLE_NAME: !Ref YoutubeVideos
      Events:
        NewVideo:
          Type: Api
          Properties:
            Path: /videos
            Method: get
  YoutubeVideos:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST